name: dscript
description: Execute standalone Dart shell scripts
version: 2.0.0
homepage: https://github.com/desktop-dart/dscript
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

executables:
  dscript:

dependencies:
  path: ^1.6.2

dev_dependencies:
  test: ^1.5.0
