name: dscript
description: A sample command-line application.
version: 0.0.1
homepage: https://github.com/tejainece/dscript
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

executables:
  dscript:

dependencies:
  path: ^1.5.1

dev_dependencies:
  test: ^0.12.0
